spring:
# Conexion a BDA
  datasource:
    url: jdbc:mysql://sql5.freesqldatabase.com:3306/sql5452129
    username: sql5452129
    password: TtNXTsJ2yt
# Configuraciones de JPA
  jpa: 
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect 
    show-sql: true
    open-in-view: false

# Logger configuracion
logging:
  file: application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.mx.pv: INFO
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR